/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <math.h>

double *
suma_1_svc(datos *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	result = argp->a + argp->b;
	return &result;
}

double *
resta_1_svc(datos *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	result = argp->a - argp->b;
	return &result;
}

double *
mul_1_svc(datos *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	result = argp->a * argp->b;
	return &result;
}

double *
div_1_svc(datos *argp, struct svc_req *rqstp)
{
	static double  result;
	/*
	 * insert server code here
	 */
	if(argp->b == 0){
		result = 0;
	}
	else{
		result = argp->a / argp->b;
	}
	return &result;
}

double *
potencia_1_svc(double *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
    result = pow(*argp,2);
	return &result;
}

double *
raizcuadrada_1_svc(int *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
    result = sqrt(*argp);
	return &result;
}

char **
menu_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	result = ANSI_COLOR_CYAN "***********************************************************************\n" ANSI_COLOR_RESET
             "1. Suma\n"
             "2. Resta\n"
             "3. Multiplicacion\n"
             "4. Division\n"
             "5. Potencia\n"
             "6. Raiz Cuadrada\n"
             ANSI_COLOR_CYAN "***********************************************************************" ANSI_COLOR_RESET;
	return &result;
}
