/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <stdio.h>
#include <stdlib.h>

void pedirDosNumeros(double *num1, double *num2);

void nprog_1(char *host)
{
	printf("Hola soy el cliente \n");
	CLIENT *clnt;
	// Variables generadas automáticamente
	double *result_1;
	datos suma_1_arg;
	double *result_2;
	datos resta_1_arg;
	double *result_3;
	datos mul_1_arg;
	double *result_4;
	datos div_1_arg;
	double *result_5;
	double potencia_1_arg;
	double *result_6;
	int raizcuadrada_1_arg;
	char **result_7;
	char *menu_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, NPROG, NVERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */
	   /*
	   result_1 = suma_1(&suma_1_arg, clnt);
	   if (result_1 == (double *)NULL)
	   {
		   clnt_perror(clnt, "call failed");
	   }
	   result_2 = resta_1(&resta_1_arg, clnt);
	   if (result_2 == (double *)NULL)
	   {
		   clnt_perror(clnt, "call failed");
	   }
	   result_3 = mul_1(&mul_1_arg, clnt);
	   if (result_3 == (double *)NULL)
	   {
		   clnt_perror(clnt, "call failed");
	   }
	   result_4 = div_1(&div_1_arg, clnt);
	   if (result_4 == (double *)NULL)
	   {
		   clnt_perror(clnt, "call failed");
	   }
	   result_5 = potencia_1(&potencia_1_arg, clnt);
	   if (result_5 == (double *)NULL)
	   {
		   clnt_perror(clnt, "call failed");
	   }
	   result_6 = raizcuadrada_1(&raizcuadrada_1_arg, clnt);
	   if (result_6 == (double *)NULL)
	   {
		   clnt_perror(clnt, "call failed");
	   }
	   result_7 = menu_1((void *)&menu_1_arg, clnt);
	   if (result_7 == (char **)NULL)
	   {
		   clnt_perror(clnt, "call failed");
	   }*/
	   //---------------------------------------------------------------------------

	do
	{
		//llamada al menú
		result_7 = menu_1((void *)&menu_1_arg, clnt);
		if (result_7 == (char **)NULL)
		{
			clnt_perror(clnt, "call failed");
			continue;
		}
		else
		{
			system("clear");
			printf("MENÚ recibido del servidor:\n%s\n", *result_7);
		}

		int opcion;
		printf(ANSI_COLOR_GREEN "Opcion: " ANSI_COLOR_RESET);
		scanf("%d", &opcion);

		switch (opcion)
		{
			double num1, num2;
			int num3;
		case 1:
			printf(ANSI_COLOR_BLUE "SUMA DE DOS NÚMEROS\n" ANSI_COLOR_RESET);
			pedirDosNumeros(&num1, &num2);

			suma_1_arg.a = num1;
			suma_1_arg.b = num2;

			result_1 = suma_1(&suma_1_arg, clnt);
			if (result_1 == (double *)NULL)
			{
				clnt_perror(clnt, "call failed");
			}
			else
			{
				printf("\nResultado de la suma: %f\n", *result_1);
			}
			break;
		case 2:
            printf(ANSI_COLOR_BLUE "RESTA DE DOS NÚMEROS\n" ANSI_COLOR_RESET);
			pedirDosNumeros(&num1, &num2);

			resta_1_arg.a = num1;
			resta_1_arg.b = num2;

			result_2 = resta_1(&resta_1_arg, clnt);
			if (result_2 == (double *)NULL)
			{
				clnt_perror(clnt, "call failed");
			}
			else
			{
				printf("\nResultado de la resta: %f\n", *result_2);
			}
			break;
		case 3:
            printf(ANSI_COLOR_BLUE "MULTIPLICACIÓN DE DOS NÚMEROS\n" ANSI_COLOR_RESET); 
			pedirDosNumeros(&num1, &num2);

			mul_1_arg.a = num1;
			mul_1_arg.b = num2;

			result_3 = mul_1(&mul_1_arg, clnt);
			if (result_3 == (double *)NULL)
			{
				clnt_perror(clnt, "call failed");
			}
			else
			{
				printf("\nResultado de la multiplicación: %f\n", *result_3);
			}
			break;
		case 4:
            printf(ANSI_COLOR_BLUE "DIVISIÓN DE DOS NÚMEROS\n" ANSI_COLOR_RESET);
			pedirDosNumeros(&num1, &num2);

			div_1_arg.a = num1;
			div_1_arg.b = num2;

			result_4 = div_1(&div_1_arg, clnt);
			if (result_4 == (double *)NULL)
			{
				clnt_perror(clnt, "call failed");
			}
			else
			{
				if (*result_4 == 0)
				{
					printf(ANSI_COLOR_RED"\nEl divisor es 0. No puede hacerse la división\n"ANSI_COLOR_RESET);
				}
				else
				{
					printf("\nResultado de la division: %f\n", *result_4);
				}
			}
			break;
		case 5:
            printf(ANSI_COLOR_BLUE "POTENCIA DE UN NÚMERO\n" ANSI_COLOR_RESET);
			printf("\n-->Introduce un número: ");
			scanf("%lf", &num1);

			potencia_1_arg = num1;

			result_5 = potencia_1(&potencia_1_arg, clnt);
			if (result_5 == (double *)NULL)
			{
				clnt_perror(clnt, "call failed");
			}
			else
			{
				printf("\nResultado de la potencia: %f\n", *result_5);
			}
			break;
		case 6:
            printf(ANSI_COLOR_BLUE "RAÍZ CUADRADA DE UN NÚMERO\n" ANSI_COLOR_RESET);
			printf("\n-->Introduce un número entero: ");
			scanf("%d", &num3);

			raizcuadrada_1_arg = num3;

			result_6 = raizcuadrada_1(&raizcuadrada_1_arg, clnt);
			if (result_6 == (double *)NULL)
			{
				clnt_perror(clnt, "call failed");
			}
			else
			{
				printf("\nResultado de la raíz cuadrada: %f\n", *result_6);
			}
			break;
		default:
			printf(ANSI_COLOR_RED "Opción incorrecta. Vuelve a introducir una opción correcta.\n" ANSI_COLOR_RESET);
			break;
		}

		printf(ANSI_COLOR_GREEN"\nPulsa cualquier tecla para continuar...\n"ANSI_COLOR_RESET);
		getchar();

	} while (getchar() != EOF);

	printf("\nSe ha pulsado CTRL + D. Sale del programa\n");

#ifndef DEBUG
		clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	nprog_1(host);
	exit(0);
}
void pedirDosNumeros(double *num1, double *num2)
{
	printf("\n-->Ingrese el primer número: ");
	scanf("%lf", num1);
	printf("-->Ingrese el segundo número: ");
	scanf("%lf", num2);
}