/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "vectores.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
programa_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		datosInit initvector_1_arg;
		vectores sumavector_1_arg;
		vectores productoescalar_1_arg;
		vectores productovectorial_1_arg;
		vectoresSaxpy saxpyoperacion_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case initVector:
		_xdr_argument = (xdrproc_t) xdr_datosInit;
		_xdr_result = (xdrproc_t) xdr_vectores;
		local = (char *(*)(char *, struct svc_req *)) initvector_1_svc;
		break;

	case sumaVector:
		_xdr_argument = (xdrproc_t) xdr_vectores;
		_xdr_result = (xdrproc_t) xdr_vec;
		local = (char *(*)(char *, struct svc_req *)) sumavector_1_svc;
		break;

	case productoEscalar:
		_xdr_argument = (xdrproc_t) xdr_vectores;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) productoescalar_1_svc;
		break;

	case productoVectorial:
		_xdr_argument = (xdrproc_t) xdr_vectores;
		_xdr_result = (xdrproc_t) xdr_vec;
		local = (char *(*)(char *, struct svc_req *)) productovectorial_1_svc;
		break;

	case saxpyOperacion:
		_xdr_argument = (xdrproc_t) xdr_vectoresSaxpy;
		_xdr_result = (xdrproc_t) xdr_vec;
		local = (char *(*)(char *, struct svc_req *)) saxpyoperacion_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (PROGRAMA, VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PROGRAMA, VERSION, programa_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PROGRAMA, VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PROGRAMA, VERSION, programa_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PROGRAMA, VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
