/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vectores.h"
#include <time.h>

void mostrar_vector(vec *vector);

void
programa_1(char *host)
{
	CLIENT *clnt;
	vectores  *result_1;
	datosInit  initvector_1_arg;
	vec  *result_2;
	vectores  sumavector_1_arg;
	float  *result_3;
	vectores  productoescalar_1_arg;
	vec  *result_4;
	vectores  productovectorial_1_arg;
	vec  *result_5;
	vectoresSaxpy  saxpyoperacion_1_arg;
	int tamano, rango;
	float escalar;
	//srand(time(NULL));

#ifndef	DEBUG
	clnt = clnt_create (host, PROGRAMA, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	/*result_1 = initvector_1(&initvector_1_arg, clnt);
	if (result_1 == (vectores *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = sumavector_1(&sumavector_1_arg, clnt);
	if (result_2 == (vec *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = productoescalar_1(&productoescalar_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = productovectorial_1(&productovectorial_1_arg, clnt);
	if (result_4 == (vec *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = saxpyoperacion_1(&saxpyoperacion_1_arg, clnt);
	if (result_5 == (vec *) NULL) {
		clnt_perror (clnt, "call failed");
	}*/

	system("clear");
	printf("Pŕactica 2. Trabajando con vectores\n");
	printf("----------------------------------------------------------------------\n");
	printf("1. Introducir el tamaño y el rango de ambos vectores\n");
	printf("\nTamaño: ");
	scanf("%d", &tamano);
	printf("Rango de los números aleatorios: ");
	scanf("%d", &rango);

	initvector_1_arg.limiteV = tamano;
	initvector_1_arg.rango = rango;

	result_1 = initvector_1(&initvector_1_arg, clnt);
	if (result_1 == (vectores *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("\nVector 1: ");
        mostrar_vector(&result_1->v1);
        printf("\nVector 2: ");
       	mostrar_vector(&result_1->v2);
        
	}
	/*printf("\nVector 1 de nuevo: ");
	for (int i = 0; i < result_1->v1.vec_len; i++)
	mostrar_vector(&result_1->v1);*/
	printf("----------------------------------------------------------------------\n");
	printf("2. Sumar ambos vectores: \n");
	result_2 = sumavector_1(result_1, clnt);
	if (result_2 == (vec *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("\nResultado de la suma: ");
		mostrar_vector(result_2);
	}
	printf("----------------------------------------------------------------------\n");
	printf("3. Producto escalar de ambos vectores\n");
	result_3 = productoescalar_1(result_1, clnt);
	if (result_3 == (float *) NULL) {

		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("\nProducto escalar: %.4f\n", *result_3);
	}
	printf("----------------------------------------------------------------------\n");
	printf("4. Producto vectorial de ambos vectores\n");
	//Si los vectores no son de tamaño 3, no puede hacerse
	if(result_1->v1.vec_len != 3 || result_1->v2.vec_len != 3)
	{
        printf("\nLos vectores deben ser tridimensionales para calcular el producto vectorial.\n");
	}
	else
	{
		result_4 = productovectorial_1(result_1, clnt);
		if (result_4 == (vec *)NULL)
		{
			clnt_perror(clnt, "call failed");
		}
		else
		{
			printf("\nResultado del producto vectorial:\n");
			mostrar_vector(result_4);
		}
	}
	printf("----------------------------------------------------------------------\n");
	printf("5. SAXPY(α,X,Y)=α*X+Y\n");
	printf("\nIntroduce el escalar del saxpy: ");
	scanf("%f", &escalar);
	
	saxpyoperacion_1_arg.numero = escalar;
	saxpyoperacion_1_arg.v1 = result_1->v1;
	saxpyoperacion_1_arg.v2 = result_1->v2;

	result_5 = saxpyoperacion_1(&saxpyoperacion_1_arg, clnt);
	if (result_5 == (vec *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("\nResultado de la operación SAXPY:\n");
    	mostrar_vector(result_5);
	}
	printf("----------------------------------------------------------------------\n");
	

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	programa_1 (host);
exit (0);
}

void mostrar_vector(vec *vector) {
	printf("[ ");
    for (int i = 0; i < vector->vec_len; i++) {
        printf("%.3f", vector->vec_val[i]);
        if (i < vector->vec_len - 1) {
            printf(", ");
        }
    }
    printf(" ]\n");
}
