/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "vectores.h"

bool_t
xdr_vec (XDR *xdrs, vec *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->vec_val, (u_int *) &objp->vec_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vectores (XDR *xdrs, vectores *objp)
{
	register int32_t *buf;

	 if (!xdr_vec (xdrs, &objp->v1))
		 return FALSE;
	 if (!xdr_vec (xdrs, &objp->v2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datosInit (XDR *xdrs, datosInit *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->limiteV))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->rango))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vectoresSaxpy (XDR *xdrs, vectoresSaxpy *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->numero))
		 return FALSE;
	 if (!xdr_vec (xdrs, &objp->v1))
		 return FALSE;
	 if (!xdr_vec (xdrs, &objp->v2))
		 return FALSE;
	return TRUE;
}
