/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "vectores.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

vectores *
initvector_1(datosInit *argp, CLIENT *clnt)
{
	static vectores clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, initVector,
		(xdrproc_t) xdr_datosInit, (caddr_t) argp,
		(xdrproc_t) xdr_vectores, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

vec *
sumavector_1(vectores *argp, CLIENT *clnt)
{
	static vec clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, sumaVector,
		(xdrproc_t) xdr_vectores, (caddr_t) argp,
		(xdrproc_t) xdr_vec, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

float *
productoescalar_1(vectores *argp, CLIENT *clnt)
{
	static float clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, productoEscalar,
		(xdrproc_t) xdr_vectores, (caddr_t) argp,
		(xdrproc_t) xdr_float, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

vec *
productovectorial_1(vectores *argp, CLIENT *clnt)
{
	static vec clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, productoVectorial,
		(xdrproc_t) xdr_vectores, (caddr_t) argp,
		(xdrproc_t) xdr_vec, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

vec *
saxpyoperacion_1(vectoresSaxpy *argp, CLIENT *clnt)
{
	static vec clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, saxpyOperacion,
		(xdrproc_t) xdr_vectoresSaxpy, (caddr_t) argp,
		(xdrproc_t) xdr_vec, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
